### ISSUE TITLE
Powerpoint Presentation

### ISSUE THREAD

**Issue by April00h** [ayay2002/OgGroup#20]
Must haves in the project: 
A) Elevator Pitch: 
1. One Min description of application 

B)Concept :
1. Motivation for Development
- We want an easy way to look up Pokemon Cards online

2. Need for Development 
- To make sure we have a site dedicated to organizing Pokemon according to abilities, power, and species making it easy for everyone to learn about Pokemon while satisfying the need for helping users that are fans of Pokémon to learn more about each one.

3. User Story 

C)Process:
1. Tech Used 
2. Breakdown of Tasks and Roles 
3. Challenges Faced 
- xyz
4.Successes Faced 
- xyz

D) Demo the Project 
E) Future Developers Directions
F) Link to Deployed Application and Github Repo

LETTERS CORRESPOND WITH SLIDES NEEDED 
NUMBERS CORRESPOND WITH INFORMATION NEEDED IN THE SLIDES 
- CORRESPOND WITH INFORMATION THAT CAN BE ENTERED

**Comment by April00h** [comment]
Grading Rubric: 
Presentation 10% of grade 

- Your group should present using Powerpoint or a similar presentation software.
- Every group member should speak during the presentation.
- Your presentation should follow the[ Project Presentation Template Links to an external site.](https://docs.google.com/presentation/d/10QaO9KH8HtUXj__81ve0SZcpO5DbMbqqQr4iPpbwKks/edit?usp=sharing)

**Comment by RugbyVeronica** [comment]
Compiling notes for the PowerPoint

**Comment by April00h** [comment]
Updated the background and Slide 1,2,4,5  updated. Notes passed to Veronica to review changes

**Comment by RugbyVeronica** [comment]
Updating the power point today.

**Comment by RugbyVeronica** [comment]
FInishing up the details. PLease feel free to go in and fix your role, add, edit what you feel works for the presentation

**Comment by April00h** [comment]
Discussing roles for presentation

**Comment by RugbyVeronica** [comment]
Completed
